name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Change this if your branch name is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: dev03.rudrayati.in  # Your cPanel domain
          username: dev03  # Your cPanel username
          key: ${{ secrets.CPANEL_SSH_KEY }}  # Add SSH private key in GitHub Secrets
          port: 22
          script: |
            cd ~/public_html  # Change this if your repo is in a subdirectory
            git pull origin main
            npm install  # If using Node.js
            pm2 restart all  # Restart Node.js (if needed)
            php artisan migrate  # If using Laravel
